name: Lint Go code

on: [push, pull_request]

jobs:
  Lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            sendmail:
              - 'server/sendmail/**/*.go'
            pricing:
              - 'server/pricing/**/*.go'
            other:
              - 'server/other/**/*.go'
          list-files: shell
      - name: Changed sendmail
        if: ${{ steps.filter.outputs.sendmail == 'true' }}
        run: export SERVICE=sendmail
      - name: Changed pricing
        if: ${{ steps.filter.outputs.pricing == 'true' }}
        run: export SERVICE=pricing
      - name: Changed other
        if: ${{ steps.filter.outputs.other == 'true' }}
        run: export SERVICE=other
      - name: Changing paths
        run: cd server/$SERVICE
      - name: Confirming paths
        run: ls -la
      - name: Linting Go code
        run: |
          cd server/$SERVICE
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0
          golangci-lint run
