name: Lint Go code

on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The "build" workflow
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.15.0" # The Go version to download (if necessary) and use.

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            sendmail:
              - 'server/sendmail/**/*.go'
            other:
              - 'server/other/**/*.go'
          list-files: shell
      - name: Changed sendmail
        if: ${{ steps.filter.outputs.sendmail == 'true' }}
        run: export SERVICE=sendmail
      - name: Changed other
        if: ${{ steps.filter.outputs.other == 'true' }}
        run: export SERVICE=other

      # Install all the dependencies
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint

      # Run build of the application
      - name: Run build
        run: go build server/$SERVICE

      # Run vet & lint on the code
      - name: Run vet & lint
        run: |
          go vet server/$SERVICE
          golint server/$SERVICE

      # # Run testing on the code
      # - name: Run testing
      #   run: cd test && go test -v
